### PR TITLE
Added beetbox config.

### PR DESCRIPTION
**Pull request by thom8**
Build project with beetbox -- https://github.com/beetboxvm/beetbox

Requires : 
- [Vagrant Hostsupdater](https://github.com/cogitatio/vagrant-hostsupdater)

`vagrant plugin install vagrant-hostsupdater`
- [Vagrant Auto-network](https://github.com/oscar-stack/vagrant-auto_network)

`vagrant plugin install vagrant-auto_network`

```
git clone --branch beetbox https://github.com/thom8/vih-build.git vih-build && cd $_
vagrant up
```

### CODE REVIEW

**Comment by lsolesen** [comment]
Thanks for the pull request, which I am guessing is based on my question here: https://github.com/geerlingguy/drupal-vm/issues/863

It looks really good, and seems that the provisioning of the box went perfectly. I did both:

```
vagrant plugin install vagrant-hostsupdater
vagrant plugin install vagrant-auto_network
```

And it worked. 

Then I did:

```
git clone --branch beetbox https://github.com/thom8/vih-build.git vih-build && cd $_
vagrant up
```

I can do ´vagrant ssh´ and get into the box.

<del>However when trying to access either http://beetbox.local/ or http://vih.local/ I just get `ERR_NAME_NOT_RESOLVED`.</del>

<del>When I tried getting just a standard Drupal VM working http://drupalvm.dev worked out of the box.</del>

**_UPDATE**_: Did not shut down my old DrupalVM box for spinning up the beetbox. Now I could access the box. However, there seems to be no files. II cannot quite figure out, where to find the Drupal installation on the beetbox vagrant box afterwards. And when going to http://vih.local I get "File not found."

**_UPDATE**_: Rerunning. Spending a lot of time on Generate Drupal site with drush make file right now, so maybe something went wrong the first time. Will update when knowing more.

Am I doing anything wrong?

See the recap of the beetbox install.

```
==> beetbox: PLAY RECAP *********************************************************************
==> beetbox: localhost                  : ok=178  changed=2    unreachable=0    failed=0   
==> beetbox: ********************************************************************************
==> beetbox: 
==> beetbox: 
==> beetbox: 888                        888    888
==> beetbox: 888                        888    888
==> beetbox: 888                        888    888
==> beetbox: 88888b.   .d88b.   .d88b.  888888 88888b.   .d88b.  888  888
==> beetbox: 888 "88b d8P  Y8b d8P  Y8b 888    888 "88b d88""88b `Y8bd8P'
==> beetbox: 888  888 88888888 88888888 888    888  888 888  888   X88K
==> beetbox: 888 d88P Y8b.     Y8b.     Y88b.  888 d88P Y88..88P .d8""8b.
==> beetbox: 88888P"   "Y8888   "Y8888   "Y888 88888P"   "Y88P"  888  888
==> beetbox: 
==> beetbox: ------------------------------------------------------------
==> beetbox: URL: http://beetbox.local/
==> beetbox: ------------------------------------------------------------
==> beetbox: 
==> beetbox: MySQL
==> beetbox: ------------------------------------------------------------
==> beetbox: Hostname: localhost or 127.0.0.1
==> beetbox: Port: 3306
==> beetbox: Database name: beetbox
==> beetbox: Username: beetbox
==> beetbox: Password: beetbox
==> beetbox: 
==> beetbox: Drupal
==> beetbox: ------------------------------------------------------------
==> beetbox: Drush alias: @beetbox.local
==> beetbox: 
==> beetbox: Developer Tools
==> beetbox: ------------------------------------------------------------
==> beetbox: Mailhog: http://beetbox.local:8025/
==> beetbox: 
==> beetbox: ------------------------------------------------------------
==> beetbox: Documentation: http://beetbox.rtfd.org
==> beetbox: ------------------------------------------------------------
```

**Comment by thom8** [comment]
looks like the project isn't being mounted into the VM, make sure you're using Vagrant `1.8.5`

https://github.com/beetboxvm/beetbox/issues/285

**Comment by lsolesen** [comment]
Second time around it got mounted correctly. Thanks for the pull request. This I will probably merge soon, when checking out how to integrate with PHPStorm etc. 

Is there any way to set file sharing type, like it is possible for DrupalVM? http://docs.drupalvm.com/en/latest/other/windows/. I have everything working on my Windows machine, but it is somewhat slow at the moment.

Also would it be possible to just have Drupal and contrib modules directly on the box - and then only the modules I am working on mounted on the host machine.

Do you have any docs on how to integrate with custom code like e.g. http://github.com/intraface/intraface.dk

Thanks a bunch for showing me this.

**Comment by thom8** [comment]
You can customise any Vagrant config with a `Vagrantfile.local` -- http://beetbox.readthedocs.io/en/latest/configuration/vagrant/Vagrantfile.local/

There's also some extended config specifically for Drupal distros, which will symlink the modules/themes from the root of the project however there's no docs atm.

Here's an example -- https://github.com/drupalmel/drupalmel/blob/master/.beetbox/config.yml

source: https://github.com/beetboxvm/ansible-role-beetbox-drupal/blob/master/tasks/build-makefile.yml#L26-L49

If you're familiar with ansible you can add custom tasks to the project -- http://beetbox.readthedocs.io/en/latest/configuration/ansible/custom-tasks/

Here's an example that installs behat dependencies with composer during the vagrant provisioning -- https://github.com/drupalmel/drupalmel/blob/master/.beetbox/tasks/post/behat.yml

Hope this helps

**Comment by lsolesen** [comment]
@thom8 It looks great. Trying to get the `drush` commands to not run soooo slow on the box. When navigating the site using a browser it is not too bad - `drush cc all`, however, takes several minutes.

**Comment by thom8** [comment]
@lsolesen which sync folder method are you using? the default Virtualbox method is very slow.

If you can work out a better solution for windows by customising the project Vagrantfile -- `/.beetbox/Vagrantfile` I'll be happy to add it to the project.

**Comment by lsolesen** [comment]
New pull request in sync with 7.x-1.x created here: https://github.com/vih/vih-build/pull/179

**Comment by lsolesen** [comment]
Merged in #179

**Pull request closed without merging**
